### PR TITLE
Improved deactivation rate with boundaries and better precision

### PR DESCRIPTION
**Pull request by jordang**
There might be evidence that the deactivation rate might be 0.99+.  These changes allow for better modelling of that.  [Pre-print](https://www.medrxiv.org/content/10.1101/2022.01.08.22268944v1.full.pdf), for reference

### CODE REVIEW

**Comment by jordang** [comment]
BTW, just to be clear, the changes don't have anything to do with the research.  They're just for consistency, realistic boundaries, and precise control.

**Comment by kawesomekhan** [comment]
Hi jordang, I appreciate the note. We are aware of this paper and have been looking into it. As it’s still a preprint, we have some concerns with how appropriate their method is. Until we have further confidence in the results I’m going to keep the values unchanged for now.

**Comment by jordang** [comment]
Yes, but I think I might have confused things mentioning the pre-print.  The changes that I submitted aren't using anything from that study.  The changes that I'm recommending are for internal consistency with the web app itself.

Specifically, for the advanced model, the default value is 0.6.  that's also the value mentioned in the study this web app is based on.  For the indoors model class itself, however, it's set as a different value.  So I am assuming it's an unintentional discrepancy that I fixed.

Additionally, I don't believe that the deactivation parameter can have values below 0 or above 1, however in the web app advanced page, it will allow negative and above 1 values.  So I added limits to prevent those values because I don't think those results make sense physically if I'm understanding it correctly.

Finally, I added more precision to the parameter adjustment.  This recommendation is the only change that is at all motivated by the pre-print, but only tangentially, because it's not a change in the parameter value itself, just changing the step value to allow a user to fine tune a little more.

I think this web app is an incredible educational tool.  Because of that, the biggest value is to allow a user to play and develop an intuitive sense.  In this case, whether the pre-print is the "right" number isn't as important as allowing the user input it and to realize that even if it's wrong, the user can see that it doesn't actually impact the final answers that much anyhow, which is really powerful.  (And not the conclusion any lay person would come to after hearing about the study.)

Does that clarify things?  (Please correct me if I just misunderstood the parameter.)

Thanks!

**Comment by kawesomekhan** [comment]
Ah ok ok, I understand now. Apparently I can't read 😛 I will take a look and incorporate these changes when I can. Thanks!

-Kasim Khan

**Comment by jordang** [comment]
Reading is overrated.😜. Thanks!

**Pull request merged**
